apache/couchdb-ci

- .travis.yml
This should fix when Travis kills the build for running too long, at the expense of us needing 7 or more separate build targets.
> Split platforms into separate Travis CI builds

- .gitignore
- bin/install-dependencies.sh
This change adds an ability to install additional packages useful
for development. This is done via placing additional scripts into
`bin/extra/` directory. The scripts are named based on package
manager used in a given distribution:
- `apt-*` for apt based distributions
- `pkg-*` for FreeBSD
- `yum-*` - for Centos
The scripts are executed in alphabetical order.
1. create script
```
mkdir -p bin/extra
cat << EOF > bin/extra/apt-rg.sh
curl -LO https://github.com/BurntSushi/ripgrep/releases/download/0.8.1/ripgrep_0.8.1_amd64.deb
sudo dpkg -i ripgrep_0.8.1_amd64.deb
EOF
chmod +x bin/extra/apt-rg.sh
```
2. Build platform `./build.sh platform debian-stretch`
3. Check the logs you should see following:
```
Preparing to unpack ripgrep_0.8.1_amd64.deb ...
Unpacking ripgrep (0.8.1) ...
Setting up …
```
> Allow execution of custom scripts to install packages

- bin/apt-dependencies.sh
Need this new helper to be able to build, now that the debian `control` file uses a python debhelper macro.
> [deb] Add dh-python helper

- .travis.yml
- README.md
- build.sh
Over in #4 we are seeing Travis build timeouts due to the length of time it takes to build, test and package CouchDB in a single Travis job.
This splits out Travis config into a matrix of platform vs. target. All of the currently supported platforms are in the matrix. The three targets are:
* `js` (build JavaScript package)
* `couch` (build and test CouchDB)
* `couch-pkg` (build the CouchDB pkgs from a dist tarball)
To simplify things, `couch-pkg` uses the official 2.2.0 dist tarball.
This is a lot more jobs (21 vs. 7) but I expect this repo to change very infrequently. Depending on how much parallelism Travis CI gives to Apache, this may even run faster than the old configuration.
> Split Travis into 3x the jobs (js, couch, couch-pkg)

- .travis.yml
- bin/apt-dependencies.sh
To match what we just did for needs in apache/couchdb#1764. Ironically the "easiest on all OSes" requires this pkg install on Debian/Ubuntu.
I'll leave `python3-virtualenv` in there for now, it won't hurt anything.
> [deb] add python3-venv pkg, see apache/couchdb#1764

- bin/install-elixir.sh
Erlang 22 travis builds need 1.7.4 to run
Issue: https://github.com/apache/couchdb/issues/2069
> Bump elixir from 1.6.6 to 1.7.4

- .travis.yml
- README.md
- build.sh
- dockerfiles/debian-buster
- files/debian.profile
* Adds Debian buster CI support
* Officially drops Debian jessie / Ubuntu trusty support
* Lintian fixes from new Debian buster
Travis will do it, but:
```
- ./build.sh base debian-buster
- ERLANGVERSION=20.3.8.22-1 ./build.sh platform debian-buster
- ERLANGVERSION=20.3.8.22-1 ./build.sh couchdb debian-buster
```
related to apache/couchdb-ci#47
One shortly to follow in couchdb-pkg
> Add debian buster, drop debian jessie/ubuntu trusty

- README.md
- bin/apt-dependencies.sh
- bin/apt-erlang.sh
- bin/install-dependencies.sh
- bin/source-erlang.sh
- bin/yum-dependencies.sh
- bin/yum-erlang.sh
- build.sh
- dockerfiles/centos-6
- dockerfiles/centos-7
- dockerfiles/centos-8
- dockerfiles/debian-buster
- dockerfiles/debian-jessie
- dockerfiles/debian-stretch
- dockerfiles/ubuntu-bionic
- dockerfiles/ubuntu-trusty
- dockerfiles/ubuntu-xenial
README.md summarises most of the changes. We now use a single Dockerfile
per OS-release combination, and pass in the architecture necessary via
environment variables to build.sh.
Multiarch changes are only tested on debian for now. Local testing
has success on arm64v8 (aarch64) and ppc64le for Debian stretch.
arm64v8 works on Debian buster, but ppc64le + Debian buster seems to
segfault whenever running Python 3, and fails when invoking pip3.
If packages for the requested version of Erlang can't be found, the
installer script now falls back to building Erlang from source,
allowing any arbitrary combination to be specified. Be careful, and
watch your build output for this fallback occuring - we prefer the
Erlang Solutions packages to building from source when possible.
Finally, this …
> Improvements to multi-architecture builds, arbitrary Erlang, bump default versions

- bin/apt-erlang.sh
This ensures our fake local package (when falling back to source install) will always override distro and Erlang Solutions erlang packages. This, in turn, ensures an orderly and correct package build process.
> Add epoch to override dist, ErlSolns packages (deb)

- bin/apt-dependencies.sh
- bin/pkg-dependencies.sh
- bin/yum-dependencies.sh
This adds support for FoundationDB to our matrix.
Right now, this has been tested with the debian* and ubuntu* images, and has been pushed for the `debian-buster-erlang-all` image.
There's some gaps before we can fully support all platforms, see: https://forums.foundationdb.org/t/package-download-questions/2037/3
> Add FoundationDB support, pass 1

- pull-all-couchdbdev-docker
Related PRs:
* #30 
* apache/couchdb#3895
* apache/couchdb#3905
Jenkins is currently removing these images on a scheduled basis, driving up build times and Docker Hub traffic.
> Add new images to keep

- bin/apt-dependencies.sh
- build.sh
- dockerfiles/ubuntu-jammy
Noticed issues with both the qemu emulator for ARM (illegal instruction) and with building Erlang from source (openssl 3.0
compatibility) so opted to use the default erlang 24 from jammy and build for amd64 architecture only for the pushed image:
```
ERLANGVERSION=default ./build.sh buildx-platform ubuntu-jammy
```
To check out the image:
```
docker pull apache/couchdbci-ubuntu:jammy-erlang-default
```
> Add ubuntu jammy

- bin/source-erlang.sh
- build.sh
Previously we completely skipped building it and also skipped ppc64le. Instead, let's build for that architecture, just without the jit for now.
Last attempt was yesterday with the latest qemu and 25.0.4 and it's still failing:
https://github.com/apache/couchdb-ci/actions/runs/3093428474/jobs/5005782105
> Build Erlang 25+ without jit for arm64

- build.sh
Previously had to edit the build.sh file but now can pass the list of platforms on the command line as:
```
BUILDX_PLATFORMS=... ./build.sh ...
```
The syntax is a bash-only thing probably but we're explicitly using bash so that's acceptable.
> Allow overriding buildx platforms on the command line

- README.md
- bin/install-dependencies.sh
- build.sh
Some of those haven't worked in more than 2 years and we've only used buildx to build both the x86 and the multi-arch images.
Ideally we wouldn't want to use proprietary Docker bits but that's the only one that works well with multi-arch builds. Perhaps Podman or other newer things can replace it soon enough.
These commands, for instance, were used to build the latest release and CI images:
```
ERLANGVERSION=24.3.4.7 ./build.sh buildx-platform-release
BUILDX_PLATFORMS=linux/amd64 ERLANGVERSION=23.3.4.18 ./build.sh buildx-platform debian-bullseye
ERLANGVERSION=24.3.4.7 ./build.sh buildx-platform debian-bullseye
BUILDX_PLATFORMS=linux/amd64 ERLANGVERSION=25.2 ./build.sh buildx-platform debian-bullseye
```
> Update default Erlang and cleanup unused commands

- build.sh
- pull-all-couchdbdev-docker
It turns out were were pruning all the active images as we a bunch of stale Erlang 19 and 20 ones in the list to keep. Update the list so it's current and add a note to the list OS image variables as a reminder to keep the cleanup script in sync.
This should hopefully save 2-3 minutes on each CI run as the most of the docker images should already be there. Previously it took about that much it looks like to fetch the images on every CI run after the prune script ran.
> Update pull-all-couchdbdev-docker script

- bin/source-erlang.sh
By itself this doesn't enable FIPS mode, just allows users to toggle Erlang's FIPS mode if their crypto library happens to support it.
After this `crypto:info_fips().` sould start returning `not_enabled` as opposed `not_supported` is it does currently.
https://www.erlang.org/docs/23/apps/crypto/fips.html
> Add --enable-fips Erlang configure option

- pull-all-couchdbdev-docker
We updated the image but forgot to update this list
So we kept removing the new images and pulling them too often, thus hitting rate limits from dockerhub.
> Refresh docker pull images

- bin/detect-os.sh
- bin/install-dependencies.sh
- bin/source-erlang.sh
- bin/yum-dependencies.sh
- build.sh
- dockerfiles/almalinux-8
- dockerfiles/almalinux-9
The current RHEL8 clone CI image `apache/couchdbci-centos:8-erlang-24.3.4.10` doesn't support s390x since it's based on `rockylinux:8` which doesn't have s390x support yet. 
This PR aims to replace the base image `rockylinux:8` with `almalinux-8`, so that s390x support could be added to RHEL8 clone CI image, and features on other arches won't be affected.
> Add s390x support for RHEL8 clone CI image

- README.md
- bin/install-dependencies.sh
- bin/install-elixir.sh
- build.sh
- dockerfiles/almalinux-8
- dockerfiles/almalinux-9
- dockerfiles/centos-7
- dockerfiles/debian-bookworm
- dockerfiles/debian-bullseye
- dockerfiles/debian-buster
- dockerfiles/ubuntu-bionic
- dockerfiles/ubuntu-focal
- dockerfiles/ubuntu-jammy
* Most node versions are now at 18, except a few which needed to be held back.
* Elixir is at 1.15
* Building is now a single command per erlang version:
```sh
ERLANGVERSION=24.3.4.14 ./build.sh buildx-platform-release
```
> Update node, elixir and improve building

- dockerfiles/almalinux-8
- dockerfiles/almalinux-9
- dockerfiles/centos-7
- dockerfiles/debian-bookworm
- dockerfiles/debian-bullseye
- dockerfiles/debian-buster
- dockerfiles/ubuntu-bionic
- dockerfiles/ubuntu-focal
- dockerfiles/ubuntu-jammy
This change makes it possible to run tests that require the Search functionality to be configured.  Therefore the test coverage could be increased and issues could be caught with the related applications, such as Dreyfus and the `text` searches in Mango.
> feat: add Java 8 to the Docker images for running Clouseau

- bin/yum-dependencies.sh
- dockerfiles/almalinux-8
- dockerfiles/almalinux-9
All supported rpm distros seems to have it.
Since something else seems to bring in java 8 rpm we uninstall it at the end leaving just the 21 as the default and the java 8 jre installed from docker (for clouseau).
> Install packaged java 21 for rpm distros

- bin/install-elixir.sh
Otherwise, `make clean` fails on dist tarballs, because we haven't run configure yet, which means we haven't install hex yet.
> Install Hex

- bin/source-erlang.sh
- pull-all-couchdbdev-docker
Try to build with `--enable-fips` option again
Trying
```
ERLANGVERSION=26.2.5.4 ./build.sh buildx-platform debian-bookworm
```
Then will need to see if crypto functions work.
> The upstream FIPS bug is fixed

- bin/apt-dependencies.sh
Also don't need to look for createrepo any longer. None of the deb distros have nowadays.
> Fix up noble-numbat install npm and fakeroot

- README.md
- dockerfiles/almalinux-8
- dockerfiles/almalinux-9
- dockerfiles/debian-bookworm
- dockerfiles/debian-bullseye
- dockerfiles/ubuntu-focal
- dockerfiles/ubuntu-jammy
- dockerfiles/ubuntu-noble
- pull-all-couchdbdev-docker
The updated value images are already built since this version was passed in as an env var but let's update the defaults as well before we forget.
> Update OTP default versions in dockerfiles

- bin/yum-dependencies.sh
Both have access to python 12 so go with that
Images already updated on dockerhub
```
docker run -it apache/couchdbci-centos:9-erlang-26.2.5.12
[jenkins@95f8cccab75f /]$ pip3 install requests==2.32.4
...
```
```
docker run -it apache/couchdbci-centos:8-erlang-26.2.5.12
[jenkins@af0fb7687676 /]$ pip3 install requests==2.32.4
...
```
> Install newer pythons on centoses
